FROM golang:1.22 AS builder

WORKDIR /app

RUN git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
ENV GOPRIVATE=github.com/relaunch-cot/*

COPY go.mod go.sum ./
RUN go mod download
  
COPY . .
  
RUN go build -o main .
  
FROM gcr.io/distroless/base-debian11

WORKDIR /app
COPY --from=builder /app/main .

CMD ["./main"]